import type { ProjectsPageContent } from '@/types/content';

export const projectsPageContent: ProjectsPageContent = {
  seo: {
    title: 'Our Projects | Khushbu Nirman Sewa Pvt Ltd',
    description:
      'Explore 500+ construction projects by Khushbu Nirman Sewa across Nepal — buildings, roads, bridges, hospitals, water supply, and energy infrastructure in all 7 provinces.',
    keywords: [
      'knsewa projects',
      'construction projects nepal',
      'building projects biratnagar',
      'infrastructure nepal',
      'government projects nepal',
    ],
  },

  hero: {
    label: 'OUR PROJECTS',
    headline: 'Building What Matters',
    description:
      'From hospitals and schools to bridges and water treatment plants — explore our portfolio of projects transforming communities across Nepal.',
    backgroundImage: '/images/banners/about-banner.jpg',
    breadcrumbs: [
      { label: 'Home', href: '/' },
      { label: 'Projects' },
    ],
  },

  stats: [
    { value: '500', label: 'Projects Completed', suffix: '+' },
    { value: '24', label: 'Active Sectors', suffix: '' },
    { value: '7', label: 'Provinces Covered', suffix: '' },
    { value: '30', label: 'Years of Delivery', suffix: '+' },
  ],

  categories: [
    'All',
    'Government',
    'Infrastructure',
    'Healthcare',
    'Educational',
    'Commercial',
  ],

  projects: [
    {
      id: 'project-1',
      slug: 'deerwalk-complex-kathmandu',
      title: 'Basement + G + 4 Building at Deerwalk Complex',
      category: 'Educational',
      clientType: 'commercial',
      client: 'Deerwalk Group Limited',
      description:
        'RCC Frame Structure (7 Storey) with Double Basement including Brick Masonry, Plaster, Electrical, Sanitary, Landscaping, HVAC, Lift Machine Fixing, Structural Steel Work.',
      location: 'Sifal, Kathmandu',
      scope: 'New Construction',
      status: 'completed',
      year: '2022',
      highlights: [
        '7-storey RCC frame structure',
        'Double basement',
        'HVAC & lift installation',
        'Full landscaping',
      ],
      faq: [
        { question: 'What is the Deerwalk Complex building project?', answer: 'KNSEWA constructed a 7-storey RCC frame structure with double basement at Deerwalk Complex in Sifal, Kathmandu for Deerwalk Group Limited. The building includes HVAC, lift systems, and full landscaping for an IT campus.' },
        { question: 'Who was the client for the Deerwalk Complex project?', answer: 'The client was Deerwalk Group Limited, a leading IT education institution based in Kathmandu, Nepal.' },
        { question: 'What type of construction is the Deerwalk Complex?', answer: 'It is a 7-storey RCC frame structure with double basement, designed for institutional and educational use, including brick masonry, electrical and sanitary work, HVAC systems, and lift installation.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-1/deerwalk-front-1.jpg',
        featured: '/images/project-galleries/project-1/deerwalk-front-1.jpg',
        gallery: [
          '/images/project-galleries/project-1/deerwalk-front-2.jpg',
          '/images/project-galleries/project-1/deerwalk-entrance-walkway.jpg',
          '/images/project-galleries/project-1/deerwalk-playground.jpg',
          '/images/project-galleries/project-1/deerwalk-building-wide.jpg',
          '/images/project-galleries/project-1/deerwalk-football-turf.jpg',
          '/images/project-galleries/project-1/deerwalk-building-angle.jpg',
        ],
      },
      seo: {
        title: 'Deerwalk Complex Building | KNSEWA Projects',
        description: '7-storey educational building with double basement at Deerwalk Complex, Sifal, Kathmandu.',
      },
    },
    {
      id: 'project-2',
      slug: 'baikunthe-drinking-water-madi',
      title: 'Baikunthe Underground Drinking Water Project',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Madi Integrated Inclusive Sustainable Development Project',
      description:
        'Over Head Tank (OHT) Construction, Pipe laying & jointing of different sizes along with household connection around the Baikunthe Underground Drinking Water Project.',
      location: 'Madi, Chitwan',
      scope: 'Water Supply',
      status: 'completed',
      year: '2022',
      highlights: [
        'Overhead tank construction',
        'Pipe laying & jointing',
        'Household connections',
      ],
      faq: [
        { question: 'What is the Baikunthe Underground Drinking Water Project?', answer: 'KNSEWA constructed an underground drinking water supply system in Madi, Chitwan, including overhead tank construction, pipe laying and jointing, and household water connections for the local community.' },
        { question: 'Who commissioned the Baikunthe water project?', answer: 'The project was commissioned by the Madi Integrated Inclusive Sustainable Development Project — a government initiative to improve rural water access in Madi, Chitwan.' },
        { question: 'What does this project deliver to the community?', answer: 'The project delivers reliable clean drinking water to households in Madi, Chitwan through an underground pipe distribution network connected to an overhead storage tank.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-2/p2-small.jpg',
        featured: '/images/project-galleries/project-2/1.jpg',
        gallery: [
          '/images/project-galleries/project-2/1.jpg',
          '/images/project-galleries/project-2/3.jpg',
        ],
      },
      seo: {
        title: 'Baikunthe Water Project | KNSEWA Projects',
        description: 'Underground drinking water supply project in Madi, Chitwan.',
      },
    },
    {
      id: 'project-3',
      slug: 'sewerage-treatment-letang',
      title: 'Sewerage and Treatment Plant in Letang',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Federal Water Supply & Sewerage Management Project, Biratnagar',
      description:
        'Treatment Plant (2 No), Pipe laying & jointing, Sewer Line Works with Chamber, 2 Storey RCC Building, Guard House, Compound Wall, Landscaping, Settling Tank, Approach Channel, Bar Screening, Oil & Grease Separator, Grit Pit, Drying Bed & Reed Bed.',
      location: 'Letang, Morang',
      scope: 'Water Treatment',
      status: 'completed',
      year: '2019',
      highlights: [
        '2 treatment plants',
        'Complete sewer line system',
        '2-storey RCC building',
        'Deep tube well',
      ],
      faq: [
        { question: 'What is the Sewerage and Treatment Plant project in Letang?', answer: 'KNSEWA constructed 2 sewerage treatment plants and a complete sewer line network in Letang, Morang. The project includes a 2-storey RCC building, guard house, compound wall, landscaping, settling tanks, bar screening, and grit pits.' },
        { question: 'Who was the client for the Letang sewerage project?', answer: 'The project was commissioned by the Federal Water Supply & Sewerage Management Project, Biratnagar — a government body managing urban sanitation infrastructure in Nepal.' },
        { question: 'What is the environmental impact of this project?', answer: 'The treatment plant safely processes municipal wastewater from Letang, preventing untreated sewage from polluting local rivers and groundwater, protecting public health and the environment.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-3/p-3-small.jpg',
        featured: '/images/project-galleries/project-3/6.jpg',
        gallery: [
          '/images/project-galleries/project-3/6.jpg',
          '/images/project-galleries/project-3/img-1.jpg',
        ],
      },
      seo: {
        title: 'Sewerage Treatment Plant Letang | KNSEWA Projects',
        description: 'Sewerage and treatment plant construction in Letang, Morang.',
      },
    },
    {
      id: 'project-4',
      slug: 'pathari-municipal-hospital',
      title: '15 Bedded Pathari Sanischare Municipal Hospital',
      category: 'Healthcare',
      clientType: 'government',
      client: 'Pathari Sanischare Municipality, Morang',
      description:
        'RCC Frame Structure (2 Storey) Building with RAMP Provision for all floors including Brick Masonry, Plaster, Electrical, Sanitary, Landscaping, HVAC, Lift Machine Fixing, Structural Steel Work. Includes Guard House and Mortuary Block.',
      location: 'Pathari, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2021',
      highlights: [
        '15-bed hospital facility',
        '2-storey RCC with ramp access',
        'HVAC & lift systems',
        'Guard house & mortuary',
      ],
      faq: [
        { question: 'What is the Pathari Sanischare Municipal Hospital project?', answer: 'KNSEWA constructed a 15-bed municipal hospital in Pathari, Morang for Pathari Sanischare Municipality. The 2-storey RCC building includes ramp access, HVAC and lift systems, a guard house, and a mortuary.' },
        { question: 'Who was the client for this hospital project?', answer: 'The project was commissioned by Pathari Sanischare Municipality, Morang, to expand healthcare access for the local community.' },
        { question: 'What is the current status of the hospital?', answer: 'The 15-bed Pathari Sanischare Municipal Hospital was completed in 2021 and is now operational, serving the Pathari area.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-4/p-4-small.jpg',
        featured: '/images/project-galleries/project-4/1.jpg',
        gallery: [
          '/images/project-galleries/project-4/1.jpg',
          '/images/project-galleries/project-4/2.jpg',
        ],
      },
      seo: {
        title: 'Pathari Municipal Hospital | KNSEWA Projects',
        description: '15-bed municipal hospital in Pathari, Morang.',
      },
    },
    {
      id: 'project-5',
      slug: 'pathari-khola-bridge',
      title: 'Buddha Marga ko Pathari Khola ma Pul (Bridge)',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Pathari Sanischare Municipality, Morang',
      description:
        'Double Lane 40m Long Prestressed Concrete (PSC) T Beam Bridge, Cast-in-situ RCC Pile of 800mm diameter (32 No x 16m) = 512 Rm, River Training and Protection Works, Wing Wall and Approach Road.',
      location: 'Pathari, Ward No-6, Morang',
      scope: 'Bridge Construction',
      status: 'completed',
      year: '2022',
      highlights: [
        '40m prestressed concrete bridge',
        '32 RCC piles (800mm)',
        'River training works',
        'Approach road construction',
      ],
      faq: [
        { question: 'What is the Pathari Khola Bridge project?', answer: 'KNSEWA constructed a 40-metre prestressed concrete bridge over the Pathari Khola on Buddha Marga in Ward No. 6, Pathari, Morang, for Pathari Sanischare Municipality.' },
        { question: 'What engineering work did this bridge involve?', answer: 'The project included 32 RCC piles (800mm), river training works to protect the riverbanks, and approach road construction connecting the bridge to the local road network.' },
        { question: 'Who commissioned the Pathari Khola Bridge?', answer: 'The bridge was commissioned by Pathari Sanischare Municipality, Morang, and was completed in 2022.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-5/p5-small.jpg',
        featured: '/images/project-galleries/project-5/1.jpg',
        gallery: [
          '/images/project-galleries/project-5/1.jpg',
          '/images/project-galleries/project-5/2.jpg',
        ],
      },
      seo: {
        title: 'Pathari Khola Bridge | KNSEWA Projects',
        description: '40m prestressed concrete bridge at Pathari, Morang.',
      },
    },
    {
      id: 'project-6',
      slug: 'jahada-municipal-hospital',
      title: '15 Bedded Municipal Hospital at Jahada',
      category: 'Healthcare',
      clientType: 'government',
      client: 'Jahada Rural Municipality, Morang',
      description:
        'RCC Frame Structure (3 Storey) Building, 800mm thickness Raft/Mat Foundation and RAMP Provision for all floors including Brick Masonry, Plaster, Electrical, Sanitary, Landscaping, HVAC, Lift and Structural Steel Work. Includes Guard House and Mortuary Block.',
      location: 'Majhare, Morang',
      scope: 'New Construction',
      status: 'completed',
      contractValue: 'NPR 149.7M',
      year: '2022',
      highlights: [
        '15-bed hospital',
        '3-storey RCC structure',
        'Raft foundation (800mm)',
        'Full ramp accessibility',
      ],
      faq: [
        { question: 'What is the Jahada Municipal Hospital project?', answer: 'KNSEWA is constructing a 15-bed municipal hospital for Jahada Rural Municipality in Majhare, Morang. The 3-storey RCC structure includes HVAC, lift, full ramp accessibility, a guard house, and mortuary block. Contract value: NPR 149.7 million.' },
        { question: 'What is the contract value of the Jahada Municipal Hospital?', answer: 'The contract value is NPR 149.7 million (approximately NPR 14.97 crore). The project is commissioned by Jahada Rural Municipality, Morang.' },
        { question: 'What is the current completion status?', answer: 'The Jahada Municipal Hospital has been completed and now serves as the primary healthcare facility for the Jahada rural community in Morang district.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-6/p-6-small.jpg',
        featured: '/images/project-galleries/project-6/1.jpg',
        gallery: [
          '/images/project-galleries/project-6/1.jpg',
          '/images/project-galleries/project-6/2.jpg',
          '/images/project-galleries/project-6/3.jpg',
        ],
      },
      seo: {
        title: 'Jahada Municipal Hospital | KNSEWA Projects',
        description: '15-bed municipal hospital at Jahada, Morang.',
      },
    },
    {
      id: 'project-7',
      slug: 'jahada-administration-building',
      title: 'Administration Building at Jahada-5',
      category: 'Government',
      clientType: 'government',
      client: 'Jahada Rural Municipality, Morang',
      description:
        'RCC Frame Structure Building including Brick Masonry, Plaster, Electrical, Sanitary, Landscaping, HVAC. Also includes Guard House, Canteen Block, Generator Shed, Vehicle Parking Shed and Boundary Wall of 250m.',
      location: 'Jahada-5, Majhare, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2022',
      highlights: [
        'Full administration complex',
        'Guard house & canteen',
        '250m boundary wall',
        'Generator & parking sheds',
      ],
      faq: [
        { question: 'What is the Administration Building at Jahada-5 project?', answer: 'KNSEWA constructed a full administration complex for Jahada Rural Municipality in Jahada-5, Majhare, Morang, including a guard house, canteen, and supporting facilities.' },
        { question: 'What facilities are included in this administration building?', answer: 'The project includes a 250-metre boundary wall, generator and parking sheds, a guard house, and a canteen alongside the main administrative building.' },
        { question: 'Who was the client for this project?', answer: 'The client was Jahada Rural Municipality, Morang, and the project was completed in 2022.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-7/p-7-small.jpg',
        featured: '/images/project-galleries/project-7/1.jpg',
        gallery: [
          '/images/project-galleries/project-7/1.jpg',
          '/images/project-galleries/project-7/3.jpg',
          '/images/project-galleries/project-7/4.jpg',
          '/images/project-galleries/project-7/5.jpg',
        ],
      },
      seo: {
        title: 'Jahada Administration Building | KNSEWA Projects',
        description: 'Administration building complex at Jahada-5, Morang.',
      },
    },
    {
      id: 'project-8',
      slug: 'pm-park-biratnagar',
      title: 'Prime Minister Park at Biratnagar',
      category: 'Government',
      clientType: 'government',
      client: 'Biratnagar Metropolitan City',
      description:
        'Boundary Wall, Decorative Boundary Wall, Drainage, Main Entrance Gate, Foot Deck, Foot Over Bridge, Monument Area, Open Air Theater, Pedestrian Open Statue Museum, PM Statue, Swimming Pool, Gazebo, GYM Centre, Landscaping and Beautification.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      contractValue: 'NPR 150.6M',
      year: '2022',
      highlights: [
        'Open air theater',
        'Swimming pool & gym',
        'Statue museum',
        'Complete landscaping',
      ],
      faq: [
        { question: 'What is the Prime Minister Park project in Biratnagar?', answer: 'KNSEWA is constructing the Prime Minister Park for Biratnagar Metropolitan City — a major public park featuring an open air theater, swimming pool, gym centre, PM statue museum, foot over bridge, and complete landscaping. Contract value: NPR 150.6 million.' },
        { question: 'What facilities does Prime Minister Park include?', answer: 'The park includes a boundary wall, main entrance gate, foot deck, foot over bridge, monument area, open air theater, pedestrian open statue museum, PM statue, swimming pool, gazebo, gym centre, and full landscaping.' },
        { question: 'What is the current status of Prime Minister Park?', answer: 'The Prime Minister Park has been completed and stands as one of the largest urban public development projects in Biratnagar, commissioned by Biratnagar Metropolitan City.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-8/1.jpg',
        featured: '/images/project-galleries/project-8/1.jpg',
        gallery: [
          '/images/project-galleries/project-8/1.jpg',
        ],
      },
      seo: {
        title: 'PM Park Biratnagar | KNSEWA Projects',
        description: 'Prime Minister Park construction at Biratnagar, Morang.',
      },
    },
    {
      id: 'project-9',
      slug: 'patan-secondary-school',
      title: 'Patan Secondary School',
      category: 'Educational',
      clientType: 'government',
      client: 'Central Level Project Implementation Unit, Kathmandu',
      description:
        'RCC Frame Structure (4 Storey) with Raft Foundation 0.5m thickness, area 1115.93 Sqm. Retrofitting of Nepal\'s Second Oldest School. Plinth Area: 1138.60 Sqm, Built-Up Area: 3409.60 Sqm.',
      location: 'Patandhoka, Lalitpur',
      scope: 'Renovation & Retrofitting',
      status: 'completed',
      year: '2021',
      highlights: [
        'Nepal\'s 2nd oldest school',
        '4-storey retrofitting',
        '3,409 sqm built-up area',
        'PM recognition award',
      ],
      faq: [
        { question: 'What is the Patan Secondary School project?', answer: 'KNSEWA completed the retrofitting and renovation of Patan Secondary School at Patandhoka, Lalitpur — Nepal\'s 2nd oldest school. The project involved a 4-storey RCC frame structure with raft foundation, totalling 3,409 sqm built-up area.' },
        { question: 'Why is Patan Secondary School significant for KNSEWA?', answer: 'This project earned KNSEWA a Letter of Appreciation from Former Prime Minister KP Sharma Oli in 2020, recognising the quality of construction and the social importance of preserving one of Nepal\'s oldest educational institutions.' },
        { question: 'Who was the client for the Patan Secondary School?', answer: 'The project was commissioned by the Central Level Project Implementation Unit, Kathmandu — a government body overseeing educational infrastructure across Nepal.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-9/top-view-small.jpg',
        featured: '/images/project-galleries/project-9/top-view.jpg',
        gallery: [
          '/images/project-galleries/project-9/top-view.jpg',
          '/images/project-galleries/project-9/patan-school-3.jpg',
          '/images/project-galleries/project-9/patan-school-6.jpg',
          '/images/awards/patan-token-distribution.jpg',
        ],
      },
      seo: {
        title: 'Patan Secondary School | KNSEWA Projects',
        description: 'Retrofitting of Patan Secondary School in Lalitpur — Nepal\'s 2nd oldest school.',
      },
    },
    {
      id: 'project-10',
      slug: 'panchkhal-sez-admin-building',
      title: 'Administrative Building at Panchkhal SEZ',
      category: 'Government',
      clientType: 'government',
      client: 'Special Economic Zone Authority, Kathmandu',
      description:
        'RCC Frame Structure, 1578 Sqm area including Brick Masonry, Plaster, Electrical, Sanitary, Landscaping, Structural Steel Work. Plinth Area: 1578 Sqm, Built-Up Area: 5256 Sqm.',
      location: 'Panchkhal, Kavrepalanchowk',
      scope: 'New Construction',
      status: 'completed',
      year: '2021',
      highlights: [
        '5,256 sqm built-up area',
        'Special Economic Zone',
        'Full MEP systems',
      ],
      faq: [
        { question: 'What is the Administrative Building at Panchkhal SEZ project?', answer: 'KNSEWA constructed a 5,256 sqm administrative building for the Special Economic Zone Authority at Panchkhal, Kavrepalanchowk, complete with full mechanical, electrical, and plumbing (MEP) systems.' },
        { question: 'Who commissioned this building?', answer: 'The project was commissioned by the Special Economic Zone Authority, Kathmandu, as part of the Panchkhal Special Economic Zone development.' },
        { question: 'When was this project completed?', answer: 'The Panchkhal SEZ administrative building was completed in 2021.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-10/p-10-small.jpg',
        featured: '/images/project-galleries/project-10/P3.jpg',
        gallery: [
          '/images/project-galleries/project-10/P3.jpg',
          '/images/project-galleries/project-10/P1.jpg',
          '/images/project-galleries/project-10/P2.jpg',
          '/images/project-galleries/project-10/240739276.jpg',
          '/images/project-galleries/project-10/241164731.jpg',
        ],
      },
      seo: {
        title: 'Panchkhal SEZ Admin Building | KNSEWA Projects',
        description: 'Administrative building and land development at Panchkhal Special Economic Zone.',
      },
    },
    {
      id: 'project-12',
      slug: 'mangadh-water-supply',
      title: 'Mangadh Sahalagani Water Supply and Sanitation',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Water Supply & Sanitation Division Office, Biratnagar',
      description:
        '255 Cum Capacity RCC Overhead Tank, 200 Cum Ground Reservoirs (2 No), 144 Cum/Hr Water Treatment Plants (3 No), Deep Tube Wells (5 No, 625m total), Submersible Pumps, Pressure Aerator Towers, Iron Removal Filters, Transformers.',
      location: 'Biratnagar, Morang',
      scope: 'Water Supply',
      status: 'completed',
      year: '2018',
      highlights: [
        '255 cum overhead tank',
        '3 water treatment plants',
        '5 deep tube wells',
        'Complete pumping system',
      ],
      faq: [
        { question: 'What is the Mangadh Sahalagani Water Supply and Sanitation project?', answer: 'KNSEWA built a complete water supply and sanitation system in Biratnagar, Morang, including a 255 cum overhead tank, 3 water treatment plants, and 5 deep tube wells.' },
        { question: 'What does this project deliver to the community?', answer: 'The project delivers treated drinking water to the Mangadh Sahalagani area through a complete pumping system connected to the overhead tank and treatment plants.' },
        { question: 'Who commissioned this water supply project?', answer: 'The project was commissioned by the Water Supply & Sanitation Division Office, Biratnagar, and was completed in 2018.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-12/p-12-small.jpg',
        featured: '/images/project-galleries/project-12/1.jpg',
        gallery: [
          '/images/project-galleries/project-12/1.jpg',
          '/images/project-galleries/project-12/2.jpg',
          '/images/project-galleries/project-12/3.jpg',
          '/images/project-galleries/project-12/4.jpg',
        ],
      },
      seo: {
        title: 'Mangadh Water Supply | KNSEWA Projects',
        description: 'Large-scale water supply and sanitation project in Biratnagar, Morang.',
      },
    },
    {
      id: 'project-13',
      slug: 'kiratichowk-birendranagar-road',
      title: 'Kiratichowk Birendranagar Road',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Infrastructure Development Office, Biratnagar',
      description:
        '8.75 Km of Asphalt Concrete Road, RCC Drain on both sides, Protection & Cross Drainage Works, Traffic Control, Management and Safety Works, Bio-engineering Works.',
      location: 'Pathari Sanischare Municipality, Morang',
      scope: 'Road Construction',
      status: 'completed',
      year: '2022',
      highlights: [
        '8.75 km asphalt road',
        'RCC drains both sides',
        'Cross drainage works',
        'Bio-engineering',
      ],
      faq: [
        { question: 'What is the Kiratichowk Birendranagar Road project?', answer: 'KNSEWA constructed an 8.75 km asphalt road connecting Kiratichowk and Birendranagar within Pathari Sanischare Municipality, Morang, complete with RCC drains on both sides.' },
        { question: 'What additional works were included in this road project?', answer: 'The project included cross drainage works and bio-engineering measures to stabilize the roadside embankments alongside the main asphalt road construction.' },
        { question: 'Who commissioned this road?', answer: 'The road was commissioned by the Infrastructure Development Office, Biratnagar, and completed in 2022.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-13/p-13-small.jpg',
        featured: '/images/project-galleries/project-13/1.jpg',
        gallery: [
          '/images/project-galleries/project-13/1.jpg',
          '/images/project-galleries/project-13/2.jpg',
          '/images/project-galleries/project-13/3.jpg',
          '/images/project-galleries/project-13/4.jpg',
        ],
      },
      seo: {
        title: 'Kiratichowk Road | KNSEWA Projects',
        description: '8.75 km asphalt road construction in Pathari Sanischare Municipality.',
      },
    },
    {
      id: 'project-14',
      slug: 'stormwater-drain-biratnagar',
      title: 'Stormwater Concrete Drain',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Biratnagar Metropolitan City',
      description:
        '1745m Long RCC Drain with RCC Cover Slab along with 2 No of Syphon.',
      location: 'Biratnagar, Morang',
      scope: 'Drainage',
      status: 'completed',
      year: '2022',
      highlights: [
        '1,745m long RCC drain',
        'RCC cover slab',
        '2 syphons',
      ],
      faq: [
        { question: 'What is the Stormwater Concrete Drain project?', answer: 'KNSEWA constructed a 1,745-metre long RCC stormwater drain in Biratnagar, Morang, for Biratnagar Metropolitan City, complete with an RCC cover slab.' },
        { question: 'What special structures were included in this drainage project?', answer: 'The project included 2 syphons to manage stormwater flow across intersecting waterways along the drain\'s route.' },
        { question: 'Who commissioned this drainage project?', answer: 'The project was commissioned by Biratnagar Metropolitan City and was completed in 2022.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-14/p-14-small.jpg',
        featured: '/images/project-galleries/project-14/2.jpg',
        gallery: [
          '/images/project-galleries/project-14/1.jpg',
          '/images/project-galleries/project-14/2.jpg',
        ],
      },
      seo: {
        title: 'Stormwater Drain | KNSEWA Projects',
        description: '1745m stormwater drainage system in Biratnagar.',
      },
    },
    {
      id: 'project-16',
      slug: 'gorkhapatra-sansthan-building',
      title: 'Gorkha Patra Sansthan Building',
      category: 'Commercial',
      clientType: 'government',
      client: 'Federal Project Implementation Unit, Morang',
      description:
        '3.5 Storey RCC frame structure Office Building, 2.5 Storey RCC Quarter Building, Canteen House, Guard House, Printing Plant & Godown. Area 1150.38 sqm, Total Floor Area 1521.60 sqm.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2019',
      highlights: [
        '3.5-storey office building',
        '2.5-storey quarter building',
        'Printing plant & godown',
        '1,521 sqm total floor area',
      ],
      faq: [
        { question: 'What is the Gorkha Patra Sansthan Building project?', answer: 'KNSEWA constructed the Gorkha Patra Sansthan building in Biratnagar, Morang, comprising a 3.5-storey office building and a 2.5-storey staff quarter building, totalling 1,521 sqm of floor area.' },
        { question: 'What facilities does this building include?', answer: 'The project includes a printing plant and godown alongside the office and staff quarter buildings, supporting Gorkha Patra Sansthan\'s publishing operations.' },
        { question: 'Who commissioned this project?', answer: 'The project was commissioned by the Federal Project Implementation Unit, Morang, and was completed in 2019.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-16/p-16-small.jpg',
        featured: '/images/project-galleries/project-16/p-16-small.jpg',
        gallery: [
          '/images/project-galleries/project-16/p-16-small.jpg',
        ],
      },
      seo: {
        title: 'Gorkhapatra Sansthan Building | KNSEWA Projects',
        description: 'Gorkhapatra Sansthan office and residential complex in Biratnagar.',
      },
    },
    {
      id: 'project-17',
      slug: 'aarohan-gurukul-theater',
      title: 'Theater Complex cum Residential School for Aarohan Gurukul',
      category: 'Commercial',
      clientType: 'government',
      client: 'Biratnagar Metropolitan City',
      description:
        'RCC Frame Structure Building, Total Floor Area 772.13 sqm. Includes Sanitary, Electrical, HVAC, Furniture Supply, Wooden Parketing and Audio Visual Installation. Theater Hall capacity 400 persons.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2021',
      highlights: [
        '400-seat theater hall',
        'Audio visual installation',
        'Wooden parketing',
        'Residential school facility',
      ],
      faq: [
        { question: 'What is the Aarohan Gurukul Theater Complex project?', answer: 'KNSEWA constructed a theater complex combined with a residential school for Aarohan Gurukul in Biratnagar, Morang, for Biratnagar Metropolitan City.' },
        { question: 'What facilities does the theater complex include?', answer: 'The complex features a 400-seat theater hall with audio-visual installation and wooden parquet flooring, alongside residential school facilities.' },
        { question: 'When was this project completed?', answer: 'The Aarohan Gurukul Theater Complex was completed in 2021.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-17/p-17-small.jpg',
        featured: '/images/project-galleries/project-17/3.jpg',
        gallery: [
          '/images/project-galleries/project-17/3.jpg',
          '/images/project-galleries/project-17/p-17-small.jpg',
        ],
      },
      seo: {
        title: 'Aarohan Gurukul Theater | KNSEWA Projects',
        description: 'Theater and residential school complex in Biratnagar.',
      },
    },
    {
      id: 'project-19',
      slug: 'civil-engineering-building-manmohan',
      title: 'Department of Civil Engineering Building',
      category: 'Educational',
      clientType: 'institutional',
      client: 'Manmohan Memorial Polytechnic, Morang',
      description: '2 Storey RCC Frame Structure Building for the Department of Civil Engineering.',
      location: 'Hattimuda-7, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2017',
      highlights: ['2-storey RCC structure', 'Educational facility'],
      faq: [
        { question: 'What is the Department of Civil Engineering Building project?', answer: 'KNSEWA constructed a 2-storey RCC building for the Department of Civil Engineering at Manmohan Memorial Polytechnic in Hattimuda-7, Morang.' },
        { question: 'Who was the client for this project?', answer: 'The client was Manmohan Memorial Polytechnic, Morang, an educational institution offering technical and engineering programs.' },
        { question: 'When was this building completed?', answer: 'The Department of Civil Engineering Building was completed in 2017.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-19/p-19-small.jpg',
        featured: '/images/project-galleries/project-19/1.jpg',
        gallery: [
          '/images/project-galleries/project-19/1.jpg',
          '/images/project-galleries/project-19/2.jpg',
        ],
      },
      seo: {
        title: 'Civil Engineering Building | KNSEWA Projects',
        description: 'Civil engineering department building at Manmohan Memorial Polytechnic.',
      },
    },
    {
      id: 'project-20',
      slug: 'paramedical-building-manmohan',
      title: 'Paramedical Building, Budhiganga-4',
      category: 'Educational',
      clientType: 'institutional',
      client: 'Manmohan Technical University, Morang',
      description:
        'Two and half storey RCC frame structure building with mat foundation (610mm thickness), 1687.36 sqm area. Plinth Area: 1544.70 sqm, Total Floor Area: 3034.76 sqm.',
      location: 'Budhiganga-4, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2022',
      highlights: [
        '2.5-storey RCC building',
        '3,034 sqm total floor area',
        'Mat foundation (610mm)',
        'Full MEP systems',
      ],
      faq: [
        { question: 'What is the Paramedical Building project at Budhiganga-4?', answer: 'KNSEWA constructed a 2.5-storey, 3,034 sqm paramedical building for Manmohan Technical University in Budhiganga-4, Morang, built on a 610mm mat foundation.' },
        { question: 'What systems were installed in this building?', answer: 'The building includes full mechanical, electrical, and plumbing (MEP) systems to support its use as a paramedical education facility.' },
        { question: 'Who was the client for this project?', answer: 'The client was Manmohan Technical University, Morang, and the project was completed in 2022.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-20/p-20-small.jpg',
        featured: '/images/project-galleries/project-20/1.jpg',
        gallery: [
          '/images/project-galleries/project-20/1.jpg',
          '/images/project-galleries/project-20/2.jpg',
          '/images/project-galleries/project-20/3.jpg',
        ],
      },
      seo: {
        title: 'Paramedical Building | KNSEWA Projects',
        description: 'Paramedical building at Manmohan Technical University, Morang.',
      },
    },
    {
      id: 'project-21',
      slug: 'district-treasury-office-biratnagar',
      title: 'District Treasury Controller Office Building',
      category: 'Government',
      clientType: 'government',
      client: 'District Treasury Controller Office, Morang',
      description: '2 Storey RCC Frame Structure Building for the District Treasury Controller Office.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2011',
      highlights: ['2-storey government office', 'RCC frame structure'],
      faq: [
        { question: 'What is the District Treasury Controller Office Building project?', answer: 'KNSEWA constructed a 2-storey RCC-frame government office building for the District Treasury Controller Office in Biratnagar, Morang.' },
        { question: 'Who was the client for this project?', answer: 'The client was the District Treasury Controller Office, Morang, a government body responsible for district-level treasury administration.' },
        { question: 'When was this building completed?', answer: 'The District Treasury Controller Office Building was completed in 2011.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-21/p-21-small.jpg',
        featured: '/images/project-galleries/project-21/1.jpg',
        gallery: [
          '/images/project-galleries/project-21/1.jpg',
          '/images/project-galleries/project-21/2.jpg',
        ],
      },
      seo: {
        title: 'Treasury Office Building | KNSEWA Projects',
        description: 'District Treasury Controller Office in Biratnagar, Morang.',
      },
    },
    {
      id: 'project-22',
      slug: 'karmachari-sanchaya-kosh-office',
      title: 'Office Building of Karmachari Sanchaya Kosh',
      category: 'Government',
      clientType: 'government',
      client: 'Employees Provident Fund (Karmachari Sanchaya Kosh), Morang',
      description:
        '2 Storey RCC Frame Structure Building, Total Floor Area 7603.74 sq.ft.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2018',
      highlights: ['2-storey office building', '7,603 sq.ft floor area'],
      faq: [
        { question: 'What is the Karmachari Sanchaya Kosh Office Building project?', answer: 'KNSEWA constructed a 2-storey, 7,603 sq.ft office building for Karmachari Sanchaya Kosh (the Employees Provident Fund) in Biratnagar, Morang.' },
        { question: 'Who was the client for this project?', answer: 'The client was Karmachari Sanchaya Kosh, Morang, Nepal\'s Employees Provident Fund.' },
        { question: 'When was this office building completed?', answer: 'The building was completed in 2018.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-22/p-22-small.jpg',
        featured: '/images/project-galleries/project-22/1.jpg',
        gallery: [
          '/images/project-galleries/project-22/1.jpg',
          '/images/project-galleries/project-22/2.jpg',
        ],
      },
      seo: {
        title: 'Karmachari Sanchaya Kosh Office | KNSEWA Projects',
        description: 'Employees Provident Fund office building in Biratnagar.',
      },
    },
    {
      id: 'project-23',
      slug: 'district-admin-office-biratnagar',
      title: 'District Administration Office, Biratnagar',
      category: 'Government',
      clientType: 'government',
      client: 'District Administration Office, Biratnagar',
      description:
        '3 Storey RCC Frame Structure Building, Plinth Area 5304.68 sq.ft, Total Floor Area 13453.55 sq.ft.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2014',
      highlights: ['3-storey government building', '13,453 sq.ft floor area'],
      faq: [
        { question: 'What is the District Administration Office project in Biratnagar?', answer: 'KNSEWA constructed a 3-storey, 13,453 sq.ft government office building for the District Administration Office in Biratnagar, Morang.' },
        { question: 'Who was the client for this project?', answer: 'The client was the District Administration Office, Biratnagar, the district\'s principal government administrative body.' },
        { question: 'When was this building completed?', answer: 'The District Administration Office building was completed in 2014.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-23/p-7-2.jpg',
        featured: '/images/project-galleries/project-23/1.jpg',
        gallery: [
          '/images/project-galleries/project-23/1.jpg',
          '/images/project-galleries/project-23/2.jpg',
        ],
      },
      seo: {
        title: 'District Admin Office | KNSEWA Projects',
        description: 'District Administration Office building in Biratnagar, Morang.',
      },
    },
    {
      id: 'project-25',
      slug: 'urban-development-office-biratnagar',
      title: 'Office Building of Urban Development & Building Construction',
      category: 'Government',
      clientType: 'government',
      client: 'Dept. of Urban Development & Building Construction, Biratnagar',
      description: '3 Storey RCC Frame Structure Building, Total Floor Area 6000 sq.ft.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2012',
      highlights: ['3-storey office building', '6,000 sq.ft floor area'],
      faq: [
        { question: 'What is the Urban Development & Building Construction Office project?', answer: 'KNSEWA constructed a 3-storey, 6,000 sq.ft office building for the Department of Urban Development & Building Construction in Biratnagar, Morang.' },
        { question: 'Who was the client for this project?', answer: 'The client was the Department of Urban Development & Building Construction, Biratnagar.' },
        { question: 'When was this office building completed?', answer: 'The building was completed in 2012.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-25/p-25-small.jpg',
        featured: '/images/project-galleries/project-25/p-25-small.jpg',
        gallery: [
          '/images/project-galleries/project-25/p-25-small.jpg',
        ],
      },
      seo: {
        title: 'Urban Development Office | KNSEWA Projects',
        description: 'Urban Development & Building Construction office in Biratnagar.',
      },
    },
    {
      id: 'project-26',
      slug: 'jamc-academic-block',
      title: 'Academic Block of Janta Aadarsha Multiple Campus (JAMC)',
      category: 'Educational',
      clientType: 'institutional',
      client: 'Purbanchal University, Biratnagar',
      description: '3 Storey RCC Frame Structure Building for Purbanchal University affiliated campus.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2022',
      highlights: ['3-storey academic block', 'University campus facility'],
      faq: [
        { question: 'What is the JAMC Academic Block project?', answer: 'KNSEWA constructed a 3-storey academic block for Janta Aadarsha Multiple Campus (JAMC) in Biratnagar, Morang, under Purbanchal University.' },
        { question: 'Who was the client for this project?', answer: 'The client was Purbanchal University, Biratnagar, for its affiliated Janta Aadarsha Multiple Campus.' },
        { question: 'When was this academic block completed?', answer: 'The JAMC academic block was completed in 2022.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-26/p-26-small.jpg',
        featured: '/images/project-galleries/project-26/1.jpg',
        gallery: [
          '/images/project-galleries/project-26/1.jpg',
        ],
      },
      seo: {
        title: 'JAMC Academic Block | KNSEWA Projects',
        description: 'Academic block at Janta Aadarsha Multiple Campus, Biratnagar.',
      },
    },
    {
      id: 'project-27',
      slug: 'inaruwa-substation-staff-quarter',
      title: 'Staff Quarter at Inaruwa Substation',
      category: 'Government',
      clientType: 'government',
      client: 'Nepal Electricity Authority (Hetauda-Dhalkebar-Inaruwa 400kV Project)',
      description:
        'Staff Quarter, Store House & Guard House at Inaruwa Substation. RCC frame building including sanitary and electrical work. Total floor area 549.78 sqm.',
      location: 'Inaruwa, Sunsari',
      scope: 'New Construction',
      status: 'completed',
      year: '2022',
      highlights: [
        'NEA 400kV substation project',
        'Staff quarters & guard house',
        '549 sqm floor area',
      ],
      faq: [
        { question: 'What is the Staff Quarter at Inaruwa Substation project?', answer: 'KNSEWA constructed a 549 sqm staff quarter and guard house at the Inaruwa Substation in Sunsari, as part of Nepal Electricity Authority\'s Hetauda-Dhalkebar-Inaruwa 400kV transmission project.' },
        { question: 'Who was the client for this project?', answer: 'The client was Nepal Electricity Authority (NEA), under its Hetauda-Dhalkebar-Inaruwa 400kV transmission line project.' },
        { question: 'When was this staff quarter completed?', answer: 'The staff quarter and guard house were completed in 2022.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-27/p-27-small.jpg',
        featured: '/images/project-galleries/project-27/1.jpg',
        gallery: [
          '/images/project-galleries/project-27/1.jpg',
          '/images/project-galleries/project-27/2.jpg',
          '/images/project-galleries/project-27/3.jpg',
          '/images/project-galleries/project-27/4.jpg',
        ],
      },
      seo: {
        title: 'Inaruwa Substation Staff Quarter | KNSEWA Projects',
        description: 'Staff quarters at NEA Inaruwa 400kV substation, Sunsari.',
      },
    },
    {
      id: 'project-31',
      slug: 'rcc-overhead-tank-biratnagar',
      title: '450 Cum Capacity RCC Overhead Tank',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Federal Water Supply & Sewerage Management Project, Biratnagar',
      description:
        '450 Cum Capacity RCC Overhead Tank, Pipe line installation & fitting Works, Installation of Submersible Pump, Leak Proof Test, Supply & Installation of Electrical Works.',
      location: 'Pichra, Biratnagar, Morang',
      scope: 'Water Supply',
      status: 'completed',
      year: '2014',
      highlights: [
        '450 cum capacity',
        'Submersible pump installation',
        'Complete electrical works',
      ],
      faq: [
        { question: 'What is the 450 Cum RCC Overhead Tank project?', answer: 'KNSEWA constructed a 450 cum capacity RCC overhead water tank at Pichra, Biratnagar, Morang, for the Federal Water Supply & Sewerage Management Project.' },
        { question: 'What mechanical and electrical work was included?', answer: 'The project included submersible pump installation and complete electrical works to operate the water distribution system.' },
        { question: 'When was this tank completed?', answer: 'The overhead tank was completed in 2014.' },
      ],
      images: {
        thumbnail: '/images/project-galleries/project-31/p-31-small.jpg',
        featured: '/images/project-galleries/project-31/p-31-small.jpg',
        gallery: [
          '/images/project-galleries/project-31/p-31-small.jpg',
        ],
      },
      seo: {
        title: 'RCC Overhead Tank | KNSEWA Projects',
        description: '450 cum RCC overhead tank at Pichra, Biratnagar.',
      },
    },

    // ── New projects from General Construction Experience PDF ──

    {
      id: 'project-34',
      slug: 'rcc-bridge-simariya-road',
      title: 'RCC Bridge Construction, Simariya Road',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Sunsari-Morang Bridge Construction Project, Sunsari',
      description: 'RCC bridge construction on Simariya Road, Morang. Part of the Sunsari-Morang Bridge Construction Project.',
      location: 'Simariya Road, Morang',
      scope: 'Bridge Construction',
      status: 'completed',
      year: '2009',
      highlights: ['RCC Bridge', 'Simariya Road', 'Sunsari-Morang Bridge Project'],
      faq: [
        { question: 'What is the RCC Bridge Construction project on Simariya Road?', answer: 'KNSEWA constructed an RCC bridge on Simariya Road in Morang, under the Sunsari-Morang Bridge Construction Project.' },
        { question: 'Who commissioned this bridge?', answer: 'The bridge was commissioned by the Sunsari-Morang Bridge Construction Project, Sunsari.' },
        { question: 'When was this bridge completed?', answer: 'The Simariya Road bridge was completed in 2009.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'RCC Bridge Simariya Road | KNSEWA Projects',
        description: 'RCC bridge construction on Simariya Road, Morang.',
      },
    },
    {
      id: 'project-35',
      slug: 'rcc-overhead-tank-mangsuwa',
      title: '450m³ RCC Overhead Water Tank, Mangsuwa',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Water Supply & Sanitation Division Office, Morang',
      description: '450m³ RCC overhead water tank construction for community water supply in Mangsuwa area.',
      location: 'Mangsuwa, Morang',
      scope: 'Water Infrastructure',
      status: 'completed',
      year: '2009',
      highlights: ['450m³ Capacity', 'RCC Construction', 'Water Supply'],
      faq: [
        { question: 'What is the RCC Overhead Water Tank project in Mangsuwa?', answer: 'KNSEWA constructed a 450m³ capacity RCC overhead water tank in Mangsuwa, Morang, for the Water Supply & Sanitation Division Office, Morang.' },
        { question: 'What does this tank provide to the community?', answer: 'The tank provides water storage and supply infrastructure to support the local drinking water network in Mangsuwa.' },
        { question: 'When was this tank completed?', answer: 'The Mangsuwa overhead tank was completed in 2009.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: '450m³ RCC Overhead Tank Mangsuwa | KNSEWA Projects',
        description: '450m³ RCC overhead water tank construction in Mangsuwa, Morang.',
      },
    },
    {
      id: 'project-36',
      slug: 'dormitory-lutheran-world-federation',
      title: '3-Storeys Dormitory Building, Lutheran World Federation',
      category: 'Commercial',
      clientType: 'institutional',
      client: 'Lutheran World Federation, Kathmandu',
      description: '3-storey dormitory building constructed for the Lutheran World Federation in Kathmandu.',
      location: 'Kathmandu',
      scope: 'Dormitory Building',
      status: 'completed',
      year: '2006',
      highlights: ['3-Storey Building', 'Dormitory Facility', 'International Organization'],
      faq: [
        { question: 'What is the Lutheran World Federation Dormitory Building project?', answer: 'KNSEWA constructed a 3-storey dormitory building in Kathmandu for the Lutheran World Federation, an international humanitarian organization.' },
        { question: 'Who was the client for this project?', answer: 'The client was the Lutheran World Federation, Kathmandu.' },
        { question: 'When was this dormitory building completed?', answer: 'The dormitory building was completed in 2006.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Dormitory Building Lutheran World Federation | KNSEWA Projects',
        description: '3-storey dormitory building for Lutheran World Federation, Kathmandu.',
      },
    },
    {
      id: 'project-37',
      slug: 'warehouse-district-election-office',
      title: 'Ware House Construction, District Election Office',
      category: 'Government',
      clientType: 'government',
      client: 'District Election Office, Morang',
      description: 'Warehouse construction for the District Election Office in Morang.',
      location: 'Morang',
      scope: 'Warehouse Construction',
      status: 'completed',
      year: '2008',
      highlights: ['Warehouse Facility', 'Government Storage', 'Election Office'],
      faq: [
        { question: 'What is the Warehouse Construction project for the District Election Office?', answer: 'KNSEWA constructed a warehouse facility for the District Election Office, Morang, to provide secure government storage.' },
        { question: 'Who was the client for this project?', answer: 'The client was the District Election Office, Morang.' },
        { question: 'When was this warehouse completed?', answer: 'The warehouse was completed in 2008.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Warehouse District Election Office | KNSEWA Projects',
        description: 'Warehouse construction for District Election Office, Morang.',
      },
    },
    {
      id: 'project-38',
      slug: 'compound-wall-ard-usaid',
      title: 'Compound Wall, Buildings, Slab Culvert & Garage',
      category: 'Government',
      clientType: 'government',
      client: 'ARD/USAID/NGCPP-Nepal',
      description: 'Construction of compound wall, buildings, slab culvert, and garage for the ARD/USAID/NGCPP-Nepal project.',
      location: 'Morang',
      scope: 'Infrastructure & Buildings',
      status: 'completed',
      year: '2010',
      highlights: ['Compound Wall', 'Slab Culvert', 'International Development Project'],
      faq: [
        { question: 'What is the ARD/USAID compound wall and buildings project?', answer: 'KNSEWA constructed a compound wall, buildings, a slab culvert, and a garage in Morang for ARD/USAID/NGCPP-Nepal, an international development program.' },
        { question: 'Who was the client for this project?', answer: 'The client was ARD/USAID/NGCPP-Nepal.' },
        { question: 'When was this project completed?', answer: 'The project was completed in 2010.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'ARD/USAID/NGCPP Infrastructure | KNSEWA Projects',
        description: 'Compound wall, buildings, slab culvert and garage for ARD/USAID/NGCPP-Nepal.',
      },
    },
    {
      id: 'project-39',
      slug: 'warehouse-district-admin-sunsari',
      title: 'Ware House & Infrastructures, District Admin Office, Sunsari',
      category: 'Government',
      clientType: 'government',
      client: 'District Admin. Office, Sunsari',
      description: 'Construction of warehouse and infrastructure including compound wall at the District Administration Office, Sunsari.',
      location: 'Sunsari',
      scope: 'Warehouse & Infrastructure',
      status: 'completed',
      year: '2011',
      highlights: ['Warehouse', 'Compound Wall', 'Government Infrastructure'],
      faq: [
        { question: 'What is the Warehouse & Infrastructures project for the District Admin Office, Sunsari?', answer: 'KNSEWA constructed a warehouse, compound wall, and supporting infrastructure for the District Administration Office in Sunsari.' },
        { question: 'Who was the client for this project?', answer: 'The client was the District Administration Office, Sunsari.' },
        { question: 'When was this project completed?', answer: 'The project was completed in 2011.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Warehouse District Admin Office Sunsari | KNSEWA Projects',
        description: 'Warehouse and infrastructure at District Admin Office, Sunsari.',
      },
    },
    {
      id: 'project-40',
      slug: 'child-correction-home-morang',
      title: 'Child Correction Home',
      category: 'Government',
      clientType: 'government',
      client: 'Mahila Bal-bikas & Samaj Kalyan, Morang',
      description: 'Construction of child correction home for the Department of Women, Children and Social Welfare in Morang.',
      location: 'Morang',
      scope: 'Institutional Building',
      status: 'completed',
      year: '2009',
      highlights: ['Child Welfare Facility', 'Government Institution', 'Social Infrastructure'],
      faq: [
        { question: 'What is the Child Correction Home project?', answer: 'KNSEWA constructed a Child Correction Home in Morang for Mahila Bal-bikas & Samaj Kalyan (Women, Children Development & Social Welfare), Morang, a government social welfare institution.' },
        { question: 'Who was the client for this project?', answer: 'The client was Mahila Bal-bikas & Samaj Kalyan, Morang.' },
        { question: 'When was this facility completed?', answer: 'The Child Correction Home was completed in 2009.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Child Correction Home | KNSEWA Projects',
        description: 'Child correction home construction in Morang.',
      },
    },
    {
      id: 'project-41',
      slug: 'pakali-mahendra-nagar-chatra-road',
      title: 'Pakali-Mahendra Nagar-Chatra Road Sub-Project',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'RRRSDP, DPO, Sunsari',
      description: 'Road sub-project under the Rural Reconstruction and Rehabilitation Sector Development Program (RRRSDP) connecting Pakali to Mahendra Nagar via Chatra.',
      location: 'Sunsari',
      scope: 'Road Construction',
      status: 'completed',
      year: '2010',
      highlights: ['Road Sub-Project', 'RRRSDP', 'Rural Road Network'],
      faq: [
        { question: 'What is the Pakali-Mahendra Nagar-Chatra Road Sub-Project?', answer: 'KNSEWA constructed a rural road connecting Pakali, Mahendra Nagar, and Chatra in Sunsari, under the Rural Reconstruction and Rehabilitation Sector Development Program (RRRSDP).' },
        { question: 'Who commissioned this road project?', answer: 'The project was commissioned by the District Project Office (DPO), Sunsari, under RRRSDP.' },
        { question: 'When was this road completed?', answer: 'The road sub-project was completed in 2010.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Pakali-Mahendra Nagar Road | KNSEWA Projects',
        description: 'Pakali-Mahendra Nagar-Chatra road sub-project in Sunsari.',
      },
    },
    {
      id: 'project-42',
      slug: 'office-ministry-agriculture-morang',
      title: 'Office Building, Ministry of Agriculture & Co-operative',
      category: 'Government',
      clientType: 'government',
      client: 'Ministry of Agriculture & Co-operative, Department of Co-operative, Division Co-operative Office (DCO), Morang, Nepal',
      description: 'Office building construction for the Ministry of Agriculture and Co-operative Department in Morang.',
      location: 'Morang',
      scope: 'Government Office',
      status: 'completed',
      year: '2012',
      highlights: ['Ministry Office', 'Co-operative Department', 'Government Building'],
      faq: [
        { question: 'What is the Ministry of Agriculture & Co-operative Office Building project?', answer: 'KNSEWA constructed a government office building in Morang for the Ministry of Agriculture & Co-operative\'s Division Co-operative Office (DCO).' },
        { question: 'Who was the client for this project?', answer: 'The client was the Ministry of Agriculture & Co-operative, Department of Co-operative, Division Co-operative Office, Morang.' },
        { question: 'When was this office building completed?', answer: 'The building was completed in 2012.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Ministry of Agriculture Office | KNSEWA Projects',
        description: 'Office building for Ministry of Agriculture & Co-operative, Morang.',
      },
    },
    {
      id: 'project-43',
      slug: 'innaruwa-duhabi-ithari-dharan-corridor',
      title: 'Infrastructure Development, Innaruwa-Duhabi-Ithari-Dharan Corridor',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Department of Urban Development and Building Construction (DUDBC), Division Office, Morang',
      description: 'SBD infrastructure development work along the Innaruwa-Duhabi-Ithari-Dharan corridor under the DUDBC program.',
      location: 'Morang',
      scope: 'Infrastructure Development',
      status: 'completed',
      year: '2012',
      highlights: ['Urban Corridor', 'DUDBC Project', 'Multi-city Infrastructure'],
      faq: [
        { question: 'What is the Innaruwa-Duhabi-Ithari-Dharan Corridor project?', answer: 'KNSEWA delivered infrastructure development works along the Innaruwa-Duhabi-Ithari-Dharan urban corridor in Morang, for the Department of Urban Development and Building Construction (DUDBC).' },
        { question: 'Who commissioned this corridor project?', answer: 'The project was commissioned by DUDBC\'s Division Office, Morang.' },
        { question: 'When was this project completed?', answer: 'The corridor infrastructure project was completed in 2012.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Innaruwa-Duhabi-Ithari-Dharan Corridor | KNSEWA Projects',
        description: 'Infrastructure development along Innaruwa-Duhabi-Ithari-Dharan corridor.',
      },
    },
    {
      id: 'project-44',
      slug: 'nepal-telecom-exchange-building',
      title: 'Exchange Building, Nepal Telecom, Biratnagar',
      category: 'Commercial',
      clientType: 'government',
      client: 'Nepal Telecom, Eastern Regional Directorate, Biratnagar',
      description: 'Construction of exchange building at Roadsesh, Biratnagar for Nepal Telecom Eastern Regional Directorate.',
      location: 'Roadsesh, Biratnagar, Morang',
      scope: 'Commercial Building',
      status: 'completed',
      year: '2013',
      highlights: ['Telecom Exchange', 'Nepal Telecom', 'Eastern Regional Directorate'],
      faq: [
        { question: 'What is the Nepal Telecom Exchange Building project?', answer: 'KNSEWA constructed a telecom exchange building at Roadsesh, Biratnagar, Morang, for Nepal Telecom\'s Eastern Regional Directorate.' },
        { question: 'Who was the client for this project?', answer: 'The client was Nepal Telecom, Eastern Regional Directorate, Biratnagar.' },
        { question: 'When was this exchange building completed?', answer: 'The building was completed in 2013.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Nepal Telecom Exchange Building | KNSEWA Projects',
        description: 'Exchange building for Nepal Telecom at Roadsesh, Biratnagar.',
      },
    },
    {
      id: 'project-45',
      slug: 'canal-structures-eastern-irrigation',
      title: 'Canal and Structures, Eastern Irrigation Development Division',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Eastern Irrigation Development Division No.-2, Sunsari',
      description: 'Construction of canal and associated structures for the Eastern Irrigation Development Division in Sunsari.',
      location: 'Sunsari',
      scope: 'Irrigation',
      status: 'completed',
      year: '2013',
      highlights: ['Canal Construction', 'Irrigation Structures', 'Eastern Region'],
      faq: [
        { question: 'What is the Canal and Structures project for Eastern Irrigation Development?', answer: 'KNSEWA constructed irrigation canals and structures in Sunsari for the Eastern Irrigation Development Division No. 2.' },
        { question: 'Who commissioned this irrigation project?', answer: 'The project was commissioned by the Eastern Irrigation Development Division No. 2, Sunsari.' },
        { question: 'When was this project completed?', answer: 'The canal and structures project was completed in 2013.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Canal & Structures Eastern Irrigation | KNSEWA Projects',
        description: 'Canal and structures for Eastern Irrigation Development Division, Sunsari.',
      },
    },
    {
      id: 'project-46',
      slug: 'desilting-cmc-chatra-main-canal',
      title: 'Desilting Works of CMC, Chatra Main Canal',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Sunsari-Morang Irrigation Project, Biratnagar',
      description: 'Desilting works of CMC on Chatra Main Canal (ch 36+200 to 39+200 km) for the Sunsari-Morang Irrigation Project.',
      location: 'Biratnagar',
      scope: 'Canal Maintenance',
      status: 'completed',
      year: '2014',
      highlights: ['Desilting Works', 'Chatra Main Canal', 'Sunsari-Morang Irrigation'],
      faq: [
        { question: 'What is the Desilting Works of CMC, Chatra Main Canal project?', answer: 'KNSEWA carried out desilting works on the Chatra Main Canal (CMC) in Biratnagar, for the Sunsari-Morang Irrigation Project.' },
        { question: 'Why is canal desilting important?', answer: 'Desilting removes accumulated sediment from the Chatra Main Canal, maintaining its water flow capacity for irrigation across the Sunsari-Morang region.' },
        { question: 'Who commissioned this maintenance project?', answer: 'The project was commissioned by the Sunsari-Morang Irrigation Project, Biratnagar, and completed in 2014.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Desilting Chatra Main Canal | KNSEWA Projects',
        description: 'Desilting works of CMC, Chatra Main Canal, Biratnagar.',
      },
    },
    {
      id: 'project-47',
      slug: 'cottage-small-industry-office',
      title: 'Cottage & Small Industry Office Building',
      category: 'Government',
      clientType: 'government',
      client: 'Cottage & Small Industry Office, Biratnagar, Morang',
      description: 'Construction of office building for the Cottage and Small Industry Office in Biratnagar.',
      location: 'Biratnagar, Morang',
      scope: 'Government Office',
      status: 'completed',
      year: '2014',
      highlights: ['Industry Office', 'Government Building', 'Biratnagar'],
      faq: [
        { question: 'What is the Cottage & Small Industry Office Building project?', answer: 'KNSEWA constructed a government office building for the Cottage & Small Industry Office in Biratnagar, Morang.' },
        { question: 'Who was the client for this project?', answer: 'The client was the Cottage & Small Industry Office, Biratnagar, Morang.' },
        { question: 'When was this office building completed?', answer: 'The building was completed in 2014.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Cottage & Small Industry Office | KNSEWA Projects',
        description: 'Cottage & Small Industry Office building construction, Biratnagar.',
      },
    },
    {
      id: 'project-48',
      slug: 'kocheni-khola-rcc-bridge',
      title: 'Kocheni Khola RCC Girder Bridge',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'District Development Committee, Biratnagar, Morang',
      description: 'Construction of Kocheni Khola RCC girder bridge in Biratnagar under the District Development Committee.',
      location: 'Biratnagar, Morang',
      scope: 'Bridge Construction',
      status: 'completed',
      year: '2014',
      highlights: ['RCC Girder Bridge', 'Kocheni Khola', 'District Development'],
      faq: [
        { question: 'What is the Kocheni Khola RCC Girder Bridge project?', answer: 'KNSEWA constructed an RCC girder bridge over the Kocheni Khola in Biratnagar, Morang, for the District Development Committee.' },
        { question: 'Who commissioned this bridge?', answer: 'The bridge was commissioned by the District Development Committee, Biratnagar, Morang.' },
        { question: 'When was this bridge completed?', answer: 'The Kocheni Khola bridge was completed in 2014.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Kocheni Khola RCC Bridge | KNSEWA Projects',
        description: 'Kocheni Khola RCC girder bridge construction in Biratnagar.',
      },
    },
    {
      id: 'project-49',
      slug: 'rcc-overhead-tank-225cum',
      title: 'RCC Overhead Water Storage Tank (225 CUm)',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Water Supply & Sanitation Division Office, Morang',
      description: 'Construction of 225 CUm capacity RCC overhead water storage tank for the Water Supply and Sanitation Division.',
      location: 'Morang',
      scope: 'Water Infrastructure',
      status: 'completed',
      year: '2015',
      highlights: ['225 CUm Capacity', 'Overhead Tank', 'Water Storage'],
      faq: [
        { question: 'What is the 225 CUm RCC Overhead Water Storage Tank project?', answer: 'KNSEWA constructed a 225 cubic-metre capacity RCC overhead water storage tank in Morang for the Water Supply & Sanitation Division Office.' },
        { question: 'Who commissioned this water tank?', answer: 'The project was commissioned by the Water Supply & Sanitation Division Office, Morang.' },
        { question: 'When was this tank completed?', answer: 'The overhead tank was completed in 2015.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'RCC Overhead Tank 225 CUm | KNSEWA Projects',
        description: 'RCC overhead water storage tank (225 CUm) construction in Morang.',
      },
    },
    {
      id: 'project-50',
      slug: 'helipad-biratnagar-airport',
      title: 'Helipad at Biratnagar Airport',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Civil Aviation Authority of Nepal, Babarmahal, Kathmandu',
      description: 'Construction of helipad at Biratnagar Airport for the Civil Aviation Authority of Nepal.',
      location: 'Biratnagar',
      scope: 'Aviation Infrastructure',
      status: 'completed',
      year: '2015',
      highlights: ['Helipad Construction', 'Biratnagar Airport', 'Civil Aviation'],
      faq: [
        { question: 'What is the Helipad at Biratnagar Airport project?', answer: 'KNSEWA constructed a helipad at Biratnagar Airport for the Civil Aviation Authority of Nepal (CAAN).' },
        { question: 'Who commissioned this aviation infrastructure?', answer: 'The project was commissioned by the Civil Aviation Authority of Nepal, Babarmahal, Kathmandu.' },
        { question: 'When was this helipad completed?', answer: 'The helipad was completed in 2015.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Helipad Biratnagar Airport | KNSEWA Projects',
        description: 'Helipad construction at Biratnagar Airport.',
      },
    },
    {
      id: 'project-51',
      slug: 'blacktopped-road-jhapa-morang',
      title: 'Blacktopped Road Construction Works, Jhapa-Morang',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Division Road Office, Morang',
      description: 'Blacktopped road construction works including drainage structures on Jhapa Baijanathpur Milanchowk 7,8,9 Katahari 2,3 Adarshanagar-Bhatigunj Road, Morang.',
      location: 'Morang',
      scope: 'Road Construction',
      status: 'completed',
      year: '2015',
      highlights: ['Blacktopped Road', 'Drainage Structures', 'Multi-location'],
      faq: [
        { question: 'What is the Blacktopped Road Construction project in Jhapa-Morang?', answer: 'KNSEWA carried out blacktopped road construction works across multiple locations in the Jhapa-Morang area, including associated drainage structures, for the Division Road Office, Morang.' },
        { question: 'Who commissioned this road project?', answer: 'The project was commissioned by the Division Road Office, Morang.' },
        { question: 'When was this project completed?', answer: 'The blacktopped road works were completed in 2015.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Blacktopped Road Jhapa-Morang | KNSEWA Projects',
        description: 'Blacktopped road construction works including drainage structures in Jhapa-Morang.',
      },
    },
    {
      id: 'project-52',
      slug: 'water-tank-simara-sez',
      title: 'Overhead Water Tank and Deep Tube Well, Simara SEZ',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Special Economic Zone Development Committee, Babarmahal, Kathmandu, Nepal',
      description: 'Construction of overhead water tank and deep tube well in GPZ of Block A, Simara SEZ, District Bara for the Special Economic Zone Development Committee.',
      location: 'Simara SEZ, Bara',
      scope: 'Water Infrastructure',
      status: 'completed',
      year: '2018',
      highlights: ['Overhead Water Tank', 'Deep Tube Well', 'Special Economic Zone'],
      faq: [
        { question: 'What is the Overhead Water Tank and Deep Tube Well project at Simara SEZ?', answer: 'KNSEWA constructed an overhead water tank and deep tube well at the Simara Special Economic Zone (SEZ) in Bara, for the Special Economic Zone Development Committee.' },
        { question: 'Who commissioned this water infrastructure?', answer: 'The project was commissioned by the Special Economic Zone Development Committee, Babarmahal, Kathmandu.' },
        { question: 'When was this project completed?', answer: 'The water tank and tube well were completed in 2018.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Water Tank Simara SEZ | KNSEWA Projects',
        description: 'Overhead water tank and deep tube well at Simara Special Economic Zone.',
      },
    },
    {
      id: 'project-53',
      slug: 'warehouse-nepal-red-cross-itahari',
      title: 'Warehouse & Boundary Wall, Nepal Red Cross Society',
      category: 'Commercial',
      clientType: 'institutional',
      client: 'Nepal Red Cross Society, Kalimati, Kathmandu',
      description: 'Construction of warehouse and boundary wall at Itahari, Sunsari for Nepal Red Cross Society.',
      location: 'Itahari, Sunsari',
      scope: 'Warehouse & Infrastructure',
      status: 'completed',
      year: '2019',
      highlights: ['Warehouse', 'Boundary Wall', 'Nepal Red Cross Society'],
      faq: [
        { question: 'What is the Nepal Red Cross Society Warehouse project?', answer: 'KNSEWA constructed a warehouse and boundary wall in Itahari, Sunsari, for the Nepal Red Cross Society.' },
        { question: 'Who was the client for this project?', answer: 'The client was the Nepal Red Cross Society, headquartered in Kalimati, Kathmandu.' },
        { question: 'When was this warehouse completed?', answer: 'The warehouse and boundary wall were completed in 2019.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Nepal Red Cross Warehouse Itahari | KNSEWA Projects',
        description: 'Warehouse and boundary wall for Nepal Red Cross Society at Itahari, Sunsari.',
      },
    },
    {
      id: 'project-54',
      slug: 'staff-quarter-nea-india-transmission',
      title: 'Staff Quarter, Store & Guard House, NEA Nepal-India Electricity',
      category: 'Government',
      clientType: 'government',
      client: 'NEA, Transmission Directorate, Nepal-India Electricity Transmission & Trade Project',
      description: 'Construction of staff quarter, store and guard house at Inaruwa, Sunsari for the Nepal-India Electricity Transmission and Trade Project under NEA Transmission Directorate.',
      location: 'Inaruwa, Sunsari',
      scope: 'Staff Quarters',
      status: 'completed',
      year: '2019',
      highlights: ['NEA Transmission Project', 'Nepal-India Electricity', 'Staff Quarter & Store'],
      faq: [
        { question: 'What is the Staff Quarter, Store & Guard House project for NEA?', answer: 'KNSEWA constructed a staff quarter, store, and guard house in Inaruwa, Sunsari, for Nepal Electricity Authority\'s Nepal-India Electricity Transmission & Trade Project.' },
        { question: 'Who was the client for this project?', answer: 'The client was Nepal Electricity Authority (NEA), Transmission Directorate.' },
        { question: 'When was this project completed?', answer: 'The staff quarter, store, and guard house were completed in 2019.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'NEA Nepal-India Transmission Staff Quarter | KNSEWA Projects',
        description: 'Staff quarter, store and guard house for NEA Nepal-India Electricity Transmission project.',
      },
    },
    {
      id: 'project-55',
      slug: 'office-infrastructures-district-admin-morang',
      title: 'Office Building & Infrastructures, District Admin Office, Morang',
      category: 'Government',
      clientType: 'government',
      client: 'District Admin. Office, Morang',
      description: 'Construction of office building and infrastructures at the District Administration Office, Morang.',
      location: 'Morang',
      scope: 'Government Office',
      status: 'completed',
      year: '2011',
      highlights: ['Office Building', 'Government Infrastructure', 'District Administration'],
      faq: [
        { question: 'What is the Office Building & Infrastructures project for the District Admin Office, Morang?', answer: 'KNSEWA constructed an office building and supporting infrastructure for the District Administration Office in Morang.' },
        { question: 'Who was the client for this project?', answer: 'The client was the District Administration Office, Morang.' },
        { question: 'When was this project completed?', answer: 'The project was completed in 2011.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'District Admin Office Morang | KNSEWA Projects',
        description: 'Office building and infrastructures at District Admin Office, Morang.',
      },
    },
    {
      id: 'project-56',
      slug: 'timai-shantinagar-water-supply-jhapa',
      title: 'Timai Shantinagar Integrated Water Supply Project',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Federal Water Supply & Sewerage Management Project, Biratnagar',
      description: 'Entire construction work of Timai Shantinagar integrated water supply project covering Buddhashanti Rural Municipality wards 4, 5, 6 & 7 in Jhapa district.',
      location: 'Buddhashanti Municipality, Jhapa',
      scope: 'Water Supply',
      status: 'completed',
      contractValue: 'NPR 114.9M',
      year: '2024',
      highlights: [
        'Integrated water supply',
        'Multi-ward coverage (4,5,6,7)',
        'Federal project',
        'Buddhashanti Municipality',
      ],
      faq: [
        { question: 'What is the Timai Shantinagar Integrated Water Supply Project?', answer: 'KNSEWA is delivering an integrated water supply system for Buddhashanti Municipality in Jhapa, covering wards 4, 5, 6, and 7, for the Federal Water Supply & Sewerage Management Project, Biratnagar.' },
        { question: 'What is the contract value of this project?', answer: 'The contract value is NPR 114.9 million.' },
        { question: 'Who commissioned this project?', answer: 'The project was commissioned by the Federal Water Supply & Sewerage Management Project, Biratnagar, in 2024.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Timai Shantinagar Water Supply | KNSEWA Projects',
        description: 'Integrated water supply project at Buddhashanti Municipality, Jhapa.',
      },
    },
    {
      id: 'project-57',
      slug: 'mch-block-purbanchal-university-morang',
      title: 'Ground Floor of MCH Block at Purbanchal University',
      category: 'Healthcare',
      clientType: 'institutional',
      client: 'Purbanchal University, Central Office (PU)',
      description: 'Construction of ground floor of MCH (Maternal and Child Health) block at Purbanchal University, Sundarharaincha, Gothgaun, Morang.',
      location: 'Sundarharaincha, Gothgaun, Morang',
      scope: 'Healthcare Facility',
      status: 'completed',
      contractValue: 'NPR 120.5M',
      year: '2025',
      highlights: [
        'MCH Block',
        'Purbanchal University campus',
        'Healthcare infrastructure',
        'Ground floor construction',
      ],
      faq: [
        { question: 'What is the MCH Block project at Purbanchal University?', answer: 'KNSEWA is constructing the ground floor of the Maternal and Child Health (MCH) Block at Purbanchal University\'s campus in Sundarharaincha, Gothgaun, Morang.' },
        { question: 'What is the contract value of this project?', answer: 'The contract value is NPR 120.5 million.' },
        { question: 'Who was the client for this project?', answer: 'The client was Purbanchal University, Central Office.' },
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'MCH Block Purbanchal University | KNSEWA Projects',
        description: 'Ground floor MCH block at Purbanchal University, Gothgaun, Morang.',
      },
    },
  ],

  cta: {
    label: 'Start Your Project',
    headline: 'Have a Project in Mind?',
    description:
      'From concept to completion, our experienced team delivers results. Let\'s discuss how we can bring your construction vision to life.',
    primaryCTA: {
      text: 'Contact Us',
      href: '/contact',
    },
    secondaryCTA: {
      text: 'Our Services',
      href: '/services',
    },
  },
};
